PresentationLayer/Controllers/SignUpController.cs
using EntityLayer.Models;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using BusinessLayer.Controllers;
using AutoMapper;

namespace PresentationLayer.Controllers
{
    public class SignUpController : Controller
    {
        private readonly BusinessLayer.Controllers.SignUpController _signUpController;
        private readonly CountriesController _countriesController;
        private readonly UniversityController _universityController;
        private readonly IMapper _mapper;

        public SignUpController(BusinessLayer.Controllers.SignUpController signUpController,
            CountriesController countriesController, IMapper mapper, UniversityController universityController)
        {
            _signUpController = signUpController;
            _countriesController = countriesController;
            _universityController = universityController;
            _mapper = mapper;
        }

        [Route("signup")]
        public async Task<IActionResult> Index()
        {
            var model = new SignUpViewModel();
            model.Countries = new List<PresentationLayer.Models.Country>();
            model.Universities = new List<Models.University>();

            var countries = await _countriesController.GetCountries();
            var universities = await _universityController.GetUniversities();

            foreach (var country in countries)
                model.Countries.Add(_mapper.Map<EntityLayer.Models.Country, PresentationLayer.Models.Country>(country));

            foreach (var uni in universities)
                model.Universities.Add(_mapper.Map<EntityLayer.Models.University, PresentationLayer.Models.University>(uni));
            
            model.Universities = model.Universities.OrderByDescending(x => x.name).ToList();

            return View(model);
        }

        [HttpPost]
        [Route("process")]
        public async Task<IActionResult> SignUp(SignUpViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var user = _mapper.Map<SignUpViewModel, User>(model);
            user.Picture = await GetBytesAsync(model.Picture);
            
            try
            {
                await _signUpController.CreateAccount(user);
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

            return RedirectToAction("Index", "SignIn");
        }

        private async Task<byte[]> GetBytesAsync(IFormFile formFile)
        {
            if (formFile is not null)
            {
                using var ms = new MemoryStream();
                await formFile.CopyToAsync(ms);
                return ms.ToArray();
            }
            
            return System.IO.File.ReadAllBytes("./wwwroot/lib/defaultProfilePic.jpeg");
        }
    }
}

PresentationLayer/Views/Shared/_Layout.cshtml
@using Newtonsoft;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PresentationLayer.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
    @if (ViewContext.RouteData.Values["Controller"].Equals("SignIn")) 
    {
        <link rel="stylesheet" href="~/css/signIn.css" asp-append-version="true" />
        <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header text-center">
                        <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form method="post" asp-action="SignIn" asp-controller="SignIn">
                        <div class="modal-body mx-3">
                            <div class="md-form mb-5">
                                <div class="txt_field1">
                                    <input type="email" name="email">
                                    <label for="SignInViewModel.Email">Email</label>
                                </div>
                            </div>

                            <div class="md-form mb-4">
                                <div class="txt_field2">
                                    <input type="password" name="password">
                                    <label for="SignInViewModel.Password">Password</label>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer d-flex justify-content-center">
                            <input type="submit" value="Sign in">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div>
            <div class="header-blue">
                <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
                    <div class="container d-flex">
                        <div class="mr-auto p-2">
                            <a class="navbar-brand" asp-action="Index" asp-controller="SignIn">Quasitor</a>
                        </div>
                        <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navcol-1">
                            @* <ul class="nav navbar-nav">
                                <li class="nav-item" role="presentation"><a class="nav-link active" href="#">Link</a></li>
                                <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Dropdown </a>
                                    <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
                                </li>
                            </ul> *@
                            @* <form class="form-inline d-flex" target="_self">
                                <div class="form-group">
                                    <label for="search-field">
                                        <i class="fa fa-search"></i>
                                    </label>
                                    <input class="form-control search-field" type="search" name="search" id="search-field" placeholder="Search...">
                                </div>
                            </form> *@
                            <div class="temp d-flex align-items-right" style="margin: 0 0 0 auto;">
                                <span class="navbar-text"> 
                                    <a href="#" class="login" data-toggle="modal" data-target="#modalLoginForm">Sign in</a>
                                </span>
                                <a class="btn btn-light action-button" role="button" asp-action="Index" asp-controller="SignUp">Sign Up</a>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    } 
    @if (ViewContext.RouteData.Values["Page"] != null && ViewContext.RouteData.Values["Page"].Equals("/signup")) { }
    @if (User.Identity.IsAuthenticated)
    {
        <style>
            .header-blue .navbar .navbar-collapse span .login {
                color:white;
            }
            .header-blue .navbar .navbar-brand:hover {
                color:white;
            }
            .header-blue .navbar .form-inline label {
                color:white;
                font-size: 18px;
            }
            .header-blue .navbar .form-inline .search-field {
                color:black;
                border: 1px solid white;
                background-color: white;
            }
        </style>
        <div>
            <div class="header-blue">
                <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search" style="background:#184C34; color:white;">
                    <div class="container d-flex">
                        <div class="mr-auto p-2">
                            <a class="navbar-brand" asp-action="Index" asp-controller="SignIn">Quasitor</a>
                        </div>
                        <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navcol-1">
                            <form class="form-inline d-flex" target="_self">
                                <div class="form-group">
                                    <label for="search-field">
                                        <i class="fa fa-search"></i>
                                    </label>
                                    <input class="form-control search-field" type="text" id="search-field" list="users-list" placeholder="Search...">
                                    <datalist id="users-list" class="autocom-box">
                                    <!-- here list are inserted from javascript -->
                                    </datalist>
                                </div>
                            </form>
                            <div class="temp d-flex align-items-right">
                                <span class="navbar-text"> 
                                    <a asp-action="Index" asp-controller="Home" class="login">Home</a>
                                    <a class="login" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Account
                                    </a>
                                    <div class="dropdown-menu" style="color: black;" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Account" asp-action="Index">Edit account</a>
                                        <a class="dropdown-item" asp-controller="Account" asp-action="ViewAccount">View profile</a>
                                    </div>
                                    <a asp-action="About" asp-controller="Home" class="login">About</a>
                                    <a asp-action="SignOutAction" asp-controller="Home" class="login">Sign out</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    }

    <div class="temp">
        <div class="test">
            @RenderBody()
        </div>

        <footer class="flex-shrink-0 py-4 text-white-50 border-top">
            <div class="container">
                <div>
                    <span>Translate:</span>
                    <div id="google_translate_element"></div>
                </div>
                <hr class="col-xs-12">
                &copy; 2022 - Quasitor
            </div>
        </footer>
    </div>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
        }
    </script>
    <script>
        $(function () {
            $("#search-field").keyup(function() {
                $('#users-list .option-user').remove();
                var searchData = $("#search-field").val();
                $.ajax({
                    url: "/Home/SearchUsers",
                    type: "post",
                    data: JSON.stringify(searchData),
                    dataType: "json",
                    contentType: "application/json;utf-8",
                    success: function (user) {
                        var list = Array.from(new Set(user));
                        console.log(list);
                        $.each(list, function(i, item) {
                            var temp = $("#users-list").append($("<option>").addClass('option-user'));
                            $('.option-user').append($("<a>").attr('href', '#').text(item.name));
                            console.log(temp);
                        });
                    }
                });
            });
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>