PresentationLayer/Models/HomeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PresentationLayer.Models
{
    public class HomeViewModel
    {
        public List<Feed>? Feed { get; set; }
        public List<Users>? Users { get; set; }
    }

    public class Feed
    {
        [Required]
        public string Title { get; set; } 
        [Required]
        public string Content { get; set; }
        public DateTime Created { get; set; }
        public string User { get; set; }
        public byte[]? Picture { get; set; }
        public string ScienceArea { get; set; }
        public string DecryptedPicture { get; set; }
        public string Email { get; set; }
    }

    public class Users
    {
        public string Email { get; set; }
        public string University { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Country { get; set; }
        public string ScienceArea { get; set; }
        public byte[] Picture { get; set; }
        public string DecryptedPicture { get; set; }
    }

    public class Search 
    {
        public string Name { get; set; }
        public string Email { get; set; }
    }
}

PresentationLayer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using BusinessLayer.Controllers;
using EntityLayer.Models;
using AutoMapper;
using Microsoft.AspNetCore.Http;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PostController _postController;
        private readonly UserController _userController;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger, IMapper mapper,
            PostController postController, UserController userController)
        {
            _logger = logger;
            _postController = postController;
            _userController = userController;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await GetAllPostsAndUsers());
        }

        [Route("about")]
        public IActionResult About()
        {
            return View("About");
        }

        [Route("signout")]
        public async Task<IActionResult> SignOutAction() 
        {
            await CustomSignOut();

            return RedirectToAction("Index", "SignIn");
        }

        [HttpPost]
        [Route("post")]
        public async Task<IActionResult> CreatePost(Feed post) 
        {
            post.User = HttpContext.User.Identity.Name;
            post.Created = DateTime.Now;

            var insert = InsertPost(post);
            var header = Request.GetTypedHeaders();
            var uri = header.Referer;

            return new RedirectResult(uri.AbsoluteUri);
        }

        [HttpPost]
        public async Task<JsonResult> SearchUsers([FromBody] string searchString)
        {
            var model = new List<Search>();
            if (!string.IsNullOrEmpty(searchString))
            {
                var users = await _userController.SearchUsers(searchString);

                foreach (var user in users)
                    model.Add(_mapper.Map<User, Search>(user));

                return Json(model.Take(model.Count).Distinct()); // Change to 5 later
            }
            return null;
        }

        private async Task InsertPost(Feed post)
        {
            _postController.CreatePost(post.Title, post.Content, post.User, post.Created);
        }

        private async Task<List<Users>> GetSuggestions(string email, HomeViewModel model, Random rnd)
        {
            model.Users = new List<Users>();
            var users = await _userController.GetSuggestions(email, string.Empty);

            foreach (var user in users)
                model.Users.Add(_mapper.Map<User, Users>(user));

            if (model.Users.Count > 3)
                return model.Users = model.Users.OrderBy(x => rnd.Next()).Take(4).ToList();
            
            return model.Users = model.Users.OrderBy(x => rnd.Next()).Take(model.Users.Count).ToList();
        }

        private async Task<List<Feed>> GetPosts(string email, HomeViewModel model)
        {
            model.Feed = new List<Feed>();
            var posts = await _postController.GetAllPost(email);

            foreach (var post in posts)
                model.Feed.Add(_mapper.Map<EntityLayer.Models.Post, Feed>(post));

            return model.Feed = model.Feed.OrderByDescending(x => x.Created).ToList();
        }

        // // private async Task<List<Search>> SearchUsers(HomeViewModel model)
        // // {
        // //     model.Search = new List<Search>();
        // //     var users = await _userController.SearchUsers();

        // //     foreach (var user in users)
        // //         model.Search.Add(_mapper.Map<User, Search>(user));

        // //     return model.Search;
        // // }

        private async Task<HomeViewModel> GetAllPostsAndUsers()
        {
            var rnd = new Random();
            var user = HttpContext.User.Identity.Name;
            var model = new HomeViewModel();

            await GetPosts(user, model);

            // await SearchUsers(model);
            
            await GetSuggestions(user, model, rnd);

            return model;
        }

        private async Task CustomSignOut() 
        {
            if (HttpContext.Request.Cookies.Count> 0) 
            {
                var siteCookies = HttpContext.Request.Cookies.Where(c => c.Key.Contains(".AspNetCore.") || c.Key.Contains("Microsoft.Authentication"));
                foreach (var cookie in siteCookies)
                {
                    Response.Cookies.Delete(cookie.Key);
                }
            }

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PresentationLayer/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using Microsoft.AspNetCore.Authorization;
using BusinessLayer.Controllers;
using EntityLayer.Models;
using AutoMapper;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserController _userController;
        private readonly PostController _postController;
        private readonly IMapper _mapper;

        public ProfileController(UserController userController, IMapper mapper, PostController postController)
        {
            _userController = userController;
            _postController = postController;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(ProfileViewModel model)
        {
            if (model.Email != HttpContext.User.Identity.Name)
                return View(await GetUser(model));
            
            return RedirectToAction("ViewAccount", "Account");
        }

        private async Task<ProfileViewModel> GetUser(ProfileViewModel model)
        {
            var rnd = new Random();
            var newModel = new ProfileViewModel();
            var user = await _userController.GetCurrentUser(model.Email);

            newModel = _mapper.Map<User, ProfileViewModel>(user);
            await GetSuggestions(model.Email, newModel, rnd);
            await GetPosts(model.Email, newModel);
            
            return newModel;
        }

        private async Task<List<Feed>> GetPosts(string email, ProfileViewModel model)
        {
            model.Posts = new List<Feed>();
            var posts = await _postController.GetCurrentUserPosts(email);

            foreach (var post in posts)
                model.Posts.Add(_mapper.Map<EntityLayer.Models.Post, Feed>(post));

            return model.Posts = model.Posts.OrderByDescending(x => x.Created).ToList();
        }

        private async Task<List<Users>> GetSuggestions(string email, ProfileViewModel model, Random rnd)
        {
            model.Users = new List<Users>();
            var users = await _userController.GetSuggestions(email, HttpContext.User.Identity.Name);

            foreach (var user in users)
                model.Users.Add(_mapper.Map<User, Users>(user));

            if (model.Users.Count > 3)
                return model.Users = model.Users.OrderBy(x => rnd.Next()).Take(4).ToList();
            
            return model.Users = model.Users.OrderBy(x => rnd.Next()).Take(model.Users.Count).ToList();
        }
    }
}

PresentationLayer/Views/Home/About.cshtml
<head>
    <link rel="stylesheet" href="~/css/about.css" asp-append-version="true" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <div class="container-about">
        <div class="bg-light">
            <div class="container py-5">
                <div class="row h-100 align-items-center py-5">
                    <div class="col-lg-6">
                        <h1 class="display-4">About us</h1>
                        <p class="lead text-muted mb-0">We are three students doing this as a thesis project for our bachelor's degree.</p>
                    </div>
                    <div class="col-lg-6 d-none d-lg-block">
                        <img src="~/Avatar_Thinking_6-512_prev_ui.png" alt="" class="img-fluid" width="400">
                    </div>
                </div>
            </div>
        </div>

        <div class="bg-white py-5">
            <div class="container py-5">
                <div class="row align-items-center">
                    <div class="col-lg-5 px-5 mx-auto">
                        <img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt="" class="img-fluid mb-4 mb-lg-0">
                    </div>
                    <div class="col-lg-6 order-2 order-lg-1">
                        <i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
                        <h2 class="font-weight-light">Background</h2>
                        <p class="font-italic text-muted mb-4">As of late Febuary 2022 a war between Russia and Ukrain broke out. As a reaction to this we saw an oportunity to help ukrainian scientist connect with scientist in Sweden.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="bg-light py-5">
            <div class="container py-5">
                <div class="row mb-4">
                    <div class="col-lg-5">
                        <h2 class="display-4 font-weight-light">Our team</h2>
                    </div>
                </div>

                <div class="row text-center">
                    <!-- Team item-->
                    <div class="col-xl-3 col-sm-6 mb-5">
                        <div class="bg-white rounded shadow-sm py-5 px-4">
                            <img src="https://bootstrapious.com/i/snippets/sn-about/avatar-3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                            <h5 class="mb-0">Gideon Mbiydzenyuy</h5><span class="small text-uppercase text-muted">Supervisor</span>
                            <ul class="social mb-0 list-inline mt-3">
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End-->
                    <!-- Team item-->
                    <div class="col-xl-3 col-sm-6 mb-5">
                        <div class="bg-white rounded shadow-sm py-5 px-4">
                            <img src="https://bootstrapious.com/i/snippets/sn-about/avatar-4.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                            <h5 class="mb-0">Linus Lindblom</h5><span class="small text-uppercase text-muted">Author - Founder</span>
                            <ul class="social mb-0 list-inline mt-3">
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End-->
                    <!-- Team item-->
                    <div class="col-xl-3 col-sm-6 mb-5">
                        <div class="bg-white rounded shadow-sm py-5 px-4">
                            <img src="https://bootstrapious.com/i/snippets/sn-about/avatar-1.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                            <h5 class="mb-0">Hugo Bäckman Ulmgren</h5><span class="small text-uppercase text-muted">Author - Founder</span>
                            <ul class="social mb-0 list-inline mt-3">
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="https://www.linkedin.com/in/hugo-b%C3%A4ckman-ulmgren-aa4323220/" class="social-link"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End-->

                    <!-- Team item-->
                    <div class="col-xl-3 col-sm-6 mb-5">
                        <div class="bg-white rounded shadow-sm py-5 px-4">
                            <img src="https://bootstrapious.com/i/snippets/sn-about/avatar-2.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                            <h5 class="mb-0">Filip Glimdén</h5><span class="small text-uppercase text-muted">Author - Founder</span>
                            <ul class="social mb-0 list-inline mt-3">
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End-->
                </div>
            </div>
        </div>
    </div>
</body>

PresentationLayer/Views/Home/Index.cshtml
@model HomeViewModel

@{
    foreach (var model in Model.Feed)
    {
        @if (model.Picture != null)
        {
            var base64 = Convert.ToBase64String(model.Picture);
            var imgSrc = String.Format("data:image/jpeg;base64, {0}", base64);
            model.DecryptedPicture = imgSrc;
        }
    }
    foreach (var model in Model.Users)
    {
        @if (model.Picture != null)
        {
            var base64 = Convert.ToBase64String(model.Picture);
            var imgSrc = String.Format("data:image/jpeg;base64, {0}", base64);
            model.DecryptedPicture = imgSrc;
        }
    }
}

<head>
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
</head>

<body>
    <div class="all-wrapper">
        <div class="site-wrapper">
            <div id="sidebar">
                <div class="container-suggestions">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title mb-3">User suggestions <i class="mdi mdi-account-multiple ms-1"></i></h4>

                            @foreach (var user in Model.Users)
                            {
                                <div class="list-group" >
                                    <a href="@Url.Action("Index", "Profile", new {Email = @user.Email})" class="list-group-item list-group-item-action">
                                        <div class="d-flex align-items-center pb-1" id="tooltips-container">
                                            <img src="@user.DecryptedPicture" class="rounded-circle img-fluid bg-transparent" alt="" width="70">
                                            <div class="w-100">
                                                <h6 class="mb-1">@user.Firstname @user.Lastname</h6>
                                                <p class="font-12 text-muted">@user.University</p>
                                                <p class="font-12 text-muted">@user.ScienceArea</p>
                                                <p class="font-12 text-muted">@user.Country</p>
                                                <p class="font-12 text-muted" name="email">@user.Email</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                </div>

            </div>
            <div class="container mb-5">
                <form method="post" asp-action="CreatePost" asp-controller="Home" class="min-form">
                    @* <div class="feed d-flex justify-content-center row"> *@
                        @* <div class="col-md-5 border-right"> *@
                            <div class="p-3">
                                <div class="feed">
                                    <div class="share border bg-white" style="margin-bottom: 30px;">
                                        <div class="d-flex flex-column inputs p-2 py-4">
                                            <input type="text" class="border-0 form-control share-input" placeholder="Title" name="title">
                                            <hr class="col-xs-12">
                                            <input type="text" class="border-0 form-control share-input" placeholder="Share your thoughts" name="content">
                                        </div>
                                        <div class="d-flex flex-row justify-content-between border-top">
                                            <div class="d-flex flex-row publish-options">
                                                <div class="align-items-center border-right p-2 share">
                                                    @* <i class="fa fa-camera text-black-50"></i>
                                                    <span class="ml-1">Photo</span> *@
                                                </div>
                                                <div class="align-items-center border-right p-2 share">
                                                    @* <i class="fa fa-video-camera text-black-50"></i>
                                                    <span class="ml-1">Video</span> *@
                                                </div>
                                                <div class="align-items-center border-right p-2 share">
                                                    @* <i class="fa fa-file text-black-50"></i>
                                                    <span class="ml-1">Files</span> *@
                                                </div>
                                            </div> 
                                            <div class="publish-button">
                                                <div class="align-items-center border-left p-2 px-5 btn publish">
                                                    <input type="submit" value="Post" class="ml-1">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    @if (Model != null) 
                                    {
                                        @foreach (var post in Model.Feed)
                                        {
                                            <div class="col-md-4">
                                                <div class="post p-3 mb-2">
                                                    <div class="icon-img"> 
                                                        <img src="@post.DecryptedPicture" class="rounded-circle img-fluid bg-transparent">
                                                    </div>
                                                    <div class="c-details">
                                                        <a href="@Url.Action("Index", "Profile", new {Email = @post.Email})" class="mb-0" style="text-decoration: none; cursor: pointer;">
                                                            @post.User
                                                        </a> 
                                                        <br>
                                                        <span>@post.Created</span>
                                                    </div>
                                                    <div class="badge">
                                                        <span>@post.ScienceArea</span> 
                                                    </div>
                                                    <div class="mt-3">
                                                        <h5 class="card-title">@post.Title</h5>
                                                        <p class="card-text">@post.Content</p>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        @* </div> *@
                    @* </div> *@
                </form>
            </div>
        </div>
    </div>
    <script>
        function getUser(email) {
            var url = '@Url.Action("Index", "Profile", new {Email = 1})';
            url = url.replace('1', email);

            $(.list-group-item).attr("href", url);
        }
    </script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</body>